### ISSUE TITLE
Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [ErickCodeman93/Evaluation_Adwebsys#1]
Resultados: Erick Alva
Ciclo: 1

Problema 1: js
El archivo de entrada y salida se encuentran fijos por lo que no es posible realizar pruebas con otros archivos

Problema 1: python
El archivo de entrada y salida se encuentran fijos por lo que no es posible realizar pruebas con otros archivos
La forma de resolver el cálculo de la ventaja es incorrecto, volver a revisar el problema
Revisar las condiciones que se pueden y deben validar de la entrada
Haz uso de excepciones y clases de ser posible

Nota: 
En la regla 5, se especifica que se tienen que resolver los dos problemas en un lenguaje que domines y al menos 1
en un lenguaje que desees aprender, sin embargo, solo encuentro 1 problema en cada lenguaje.

**Comment by ErickCodeman93** [comment]
Hola, ya puedes encontrar las correcciones en mi commit más actualizado con respecto a los archivos;  agregue parámetros en las opciones del comando que ejecutan el script para elegir los archivos de entrada y salida.

Hice una restructura de mi código orientado a objetos y el uso de estructuras que ayudaron tratar de mejor forma las excepciones de los script.

Corregí la forma de resolver el problema dos ( espero que si sea la correcta ).

Tome el problema dos para hacerlo en dos lenguajes distintos, lo hice en JavaScript ( ya que es con el que más he trabajado ) y en Python ( debido a que lo he usado muy poco, pero se me hace increíble. )
