### ISSUE TITLE
Prueba 2

### ISSUE THREAD

**Issue by nbxandresvejar** [ErickCodeman93/Evaluation_Adwebsys#2]
Problema 1: js
No se pudieron realizar las pruebas, envió la salida de cada llamada.

🔥 problem_1_js node issue_1.js -i ../../casos/P1-CP1-EntradaEjemplo.txt -o salida.txt
1 node issue_1 -i <inputFile> -o <outputFile> or node issue_1 --ifile <inputFile> --ofile <outputFile>

🔥 problem_1_js node issue_1.js --ifile ../../casos/P1-CP1-EntradaEjemplo.txt -ofile salida.txt
Options:
      --help     Show help                                             [boolean]
      --version  Show version number                                   [boolean]
  -i, --ifile                                                           [string]
  -o, --ofile                                                           [string]

Problema 2: js
No se puede ejecutar el problema:
🔥 problem_2_js node issue_2.js -i ../../casos/P2-CP01-Ejemplo.txt -o salida.txt
node issue_2 -i <inputFile> -o <outputFile> or node issue_2 --ifile <inputFile> --ofile <outputFile>

🔥 problem_2_js node issue_2.js -ifile ../../casos/P2-CP01-Ejemplo.txt -ofile salida.txt 
Options:
      --help     Show help                                             [boolean]
      --version  Show version number                                   [boolean]
  -i, --ifile                                                           [string]
  -o, --ofile                                                           [string]

node issue_2 -i <inputFile> -o <outputFile> or node issue_2 --ifile <inputFile> --ofile <outputFile>

Problema 2: python
No se puede ejecutar
🐳 problem_2_py python3 issue_2.py -i ../../casos/P2-CP01-Ejemplo.txt -o salida.txt
issue_2.py -i <inputFile> -o <outputFile>
issue_2.py --ifile <inputFile> --ofile <outputFile>

**Comment by ErickCodeman93** [comment]
La corrección de la entrada y salida de los archivos quedo resuelta .
Solo queda aclarar que los parámetros pasados a los scripts son los siguientes:

Largos

-  --ifile
- --ofile

Cortos

- -i
- -o

Para cualquiera de los tres problemas funciona de la misma manera y aquí un ejemplo:

`node issue_1 -i ../../CASOS/P2-CP01-Ejemplo.txt  --ofile salida.txt`

`node issue_2 -i ../../CASOS/P2-CP01-Ejemplo.txt -o salida.txt`

`python3 issue_2.py --ifile ../../CASOS/P2-CP01-Ejemplo.txt -o
salida.txt`
